### ISSUE TITLE
FSAL is started before its basepath is created/accessible

### ISSUE THREAD

**Issue by goodbadwolf** [Outernet-Project/orx-rpi#7]
FSAL fails to start with traceback

```
[2015-11-19 18:51:59 18:51:59 (+0000)] ERROR    Unhandled exception
Traceback (most recent call last):
  File "/usr/bin/fsal-daemon", line 9, in <module>
    load_entry_point('fsal==0.0.1', 'console_scripts', 'fsal-daemon')()
  File "/usr/lib/python2.7/site-packages/fsal/daemon.py", line 57, in main
    fsal.server.main()
  File "/usr/lib/python2.7/site-packages/fsal/server.py", line 189, in main
    fs_manager = FSDBManager(config, context)
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 62, in __init__
    raise RuntimeError('Invalid basepath: "%s"' % (base_path))
RuntimeError: Invalid basepath: "/mnt/data/downloads"
```

We can see that /mnt/data/downloads is created/made accessible after FSAL starts 

```
ls -ale  /mnt/data/
total 0
drwxr-xr-x    5 root     root             0 Thu Nov 19 18:52:04 2015 .
drwxr-xr-x    4 root     root             0 Wed Nov 18 21:14:27 2015 ..
drwxr-xr-x    2 root     root             0 Thu Nov 19 18:52:04 2015 downloads
drwxrwxrwx    2 root     root             0 Thu Nov 19 18:51:59 2015 fsal
drwxr-xr-x    2 root     root             0 Thu Nov 19 18:52:04 2015 librarian
```

**Comment by foxbunny** [comment]
This is actually an issue with failing hotplug. Closing. Please reopen if issue persists once hotplug is fixed.
